//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalCarRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingData
    {
        public string PickupPoint { get; set; }
        public string DropLocation { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Car { get; set; }
    }
}
