//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalCarRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactTBL
    {
        public string fName { get; set; }
        public string mailId { get; set; }
        public decimal mobile { get; set; }
        public string message { get; set; }
    }
}
