//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalCarRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class PassengerData
{
    [Required]
    [Display(Name = "First Name")]
    public string firstName { get; set; }

    [Required]
    [Display(Name = "Last Name")]
    public string lastName { get; set; }

    [Required]
    [EmailAddress]
    public string email { get; set; }

    [Required]
    [Phone]
    [StringLength(10, MinimumLength = 10)]
    public string mobile { get; set; }

    [Required]
    [DataType(DataType.Password)]
    [MinLength(6)]
    public string pass { get; set; }
}
}
