//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalCarRentalSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoyalCarDataEntities : DbContext
    {
        public RoyalCarDataEntities()
            : base("name=RoyalCarDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminTbl> AdminTbls { get; set; }
        public DbSet<BookingData> BookingDatas { get; set; }
        public DbSet<ContactTBL> ContactTBLs { get; set; }
        public DbSet<PassengerData> PassengerDatas { get; set; }
    }
}
